language: go
go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

sudo: required

before_install:
  - git clone https://github.com/libuv/libuv.git
  - cd libuv
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
